### ISSUE TITLE
Blog Pagination

### ISSUE THREAD

**Issue by deepanshu88** [oxygenna-themes/foxi-astro-theme#4]
Thanks for the template. Can we have blog pagination feature i.e.  numbered pagination to indicate the previous page or the next page?

**Comment by elenikoundouraki** [comment]
Hello deepanshu88, thank you for your feedback! We’re glad you’re interested in the pagination feature. Numbered pagination, along with i18n localization, sliders, mega menus, and integration with Keystatic CMS, will all be available in the Pro version of Foxi!

**Comment by elenikoundouraki** [comment]
Hello deepanshu88, thank you for your feedback! We’re glad you’re interested in the pagination feature. Numbered pagination, along with i18n localization, sliders, mega menus, and integration with Keystatic CMS, will all be available in the Pro version of Foxi!
